services:
  db:
    image: bitnami/postgresql:15
    container_name: summary-review-db
    ports:
      - "5432:5432"
    hostname: db
    volumes:
      - db-data:/bitnami/postgresql:rw
    environment:
      POSTGRESQL_DATABASE: thao1711nguyen
      POSTGRESQL_USERNAME: thao1711nguyen
      POSTGRESQL_PASSWORD: 123

  backend:
    build:
      context: ./ 
      dockerfile: Dockerfile
    container_name: summary-review-app
    hostname: summary-review
    ports:
      - "81:80"
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app:rw
      - /usr/src/app/storage
      - /usr/src/app/tmp
      - /usr/src/app/log
    environment:
      VIRTUAL_HOST: backend
      VIRTUAL_PORT: "80"
      HTTPS_METHOD: "noredirect"
      DBHOST: db
      DBUSER: thao1711nguyen
      DBPASSWORD: 123
      RAILS_ENV: development
volumes:
  db-data:
    name: summary-review-db-data
    driver: local